import type { Language } from "../../lib/i18n";

type SlugMap = Record<Language, string>;

type MappingItem = {
  id: string;
  slugs: SlugMap;
};

/**
 * Brand slug mapping: {name}-chegirmalar/skidki/deals
 * Auto-generated by scripts/migrations/generate-slug-mappings.ts — review before apply.
 */
export const BRAND_SLUG_MAPPING: MappingItem[] = [
  {
    id: "26c15ea1-56cd-4c0c-9d5a-64352d20fc7c",
    slugs: {
      uz: "wildberries-chegirmalar",
      ru: "wildberries-skidki",
      en: "wildberries-deals",
    },
  },
  {
    id: "ca10614f-7a9c-43ea-adc4-c1ac28f5e79b",
    slugs: {
      uz: "zoodmall-chegirmalar",
      ru: "zoodmall-skidki",
      en: "zoodmall-deals",
    },
  },
  {
    id: "235fca05-bc7f-4ab3-abe7-376ae5dc0e60",
    slugs: {
      uz: "yandex-eats-chegirmalar",
      ru: "yandeks-eda-skidki",
      en: "yandex-eats-deals",
    },
  },
  {
    id: "3e567507-b60e-4f70-8ef4-19afc982bf8a",
    slugs: {
      uz: "tbc-bank-chegirmalar",
      ru: "tbc-bank-skidki",
      en: "tbc-bank-deals",
    },
  },
  {
    id: "b3cd6a7f-eb99-4912-943f-5dba771b758a",
    slugs: {
      uz: "uzum-bank-chegirmalar",
      ru: "uzum-bank-skidki",
      en: "uzum-bank-deals",
    },
  },
  {
    id: "5e7628b7-acea-409e-aa5b-3ad11a0663d2",
    slugs: {
      uz: "glm-ai-chegirmalar",
      ru: "glm-ai-skidki",
      en: "glm-ai-deals",
    },
  },
  {
    id: "5f79cd7b-ba26-444a-aa0f-e7541bcd04db",
    slugs: {
      uz: "iherb-chegirmalar",
      ru: "iherb-skidki",
      en: "iherb-deals",
    },
  },
  {
    id: "d01b6a70-626c-4051-9116-bcf2f5e94830",
    slugs: {
      uz: "mutolaa-chegirmalar",
      ru: "mutolaa-skidki",
      en: "mutolaa-deals",
    },
  },
  {
    id: "4b8eb481-1fc2-47bf-b8d4-17786aae08eb",
    slugs: {
      uz: "hostinger-chegirmalar",
      ru: "hostinger-skidki",
      en: "hostinger-deals",
    },
  },
  {
    id: "7d028aed-d715-455f-bb6a-8e54f688e3ed",
    slugs: {
      uz: "digitalocean-chegirmalar",
      ru: "digitalocean-skidki",
      en: "digitalocean-deals",
    },
  },
  {
    id: "0868bccb-3a6a-4d5c-8dac-234f0b001322",
    slugs: {
      uz: "railway-chegirmalar",
      ru: "railway-skidki",
      en: "railway-deals",
    },
  },
  {
    id: "b6cf1887-9f53-4ee3-81ee-25d2dfee720e",
    slugs: {
      uz: "v0-chegirmalar",
      ru: "v0-skidki",
      en: "v0-deals",
    },
  },
  {
    id: "acab32a8-d0d1-4bd0-9869-0ce17380fdc5",
    slugs: {
      uz: "jet-chegirmalar",
      ru: "jet-skidki",
      en: "jet-deals",
    },
  },
  {
    id: "735253b7-512b-42b1-8a59-2790b86f9145",
    slugs: {
      uz: "domo-chegirmalar",
      ru: "domo-skidki",
      en: "domo-deals",
    },
  },
  {
    id: "25c3b7e0-b1f1-4428-a9fb-acdb49e9f19a",
    slugs: {
      uz: "jett-chegirmalar",
      ru: "jett-skidki",
      en: "jett-deals",
    },
  },
  {
    id: "72d289ab-1f41-44da-8069-429e52ad2f14",
    slugs: {
      uz: "ibrat-akademy-chegirmalar",
      ru: "ibrat-akademy-skidki",
      en: "ibrat-akademy-deals",
    },
  },
  {
    id: "9872fb19-b239-4ade-8965-910ff749a011",
    slugs: {
      uz: "opal-chegirmalar",
      ru: "opal-skidki",
      en: "opal-deals",
    },
  },
  {
    id: "c0c98a06-f2f3-4ea0-a80e-d7cfebcc4257",
    slugs: {
      uz: "hevy-chegirmalar",
      ru: "hevy-skidki",
      en: "hevy-deals",
    },
  },
  {
    id: "ba9196db-7bba-45dc-8ab3-c2a1ebf3dfd6",
    slugs: {
      uz: "1fit-chegirmalar",
      ru: "1fit-skidki",
      en: "1fit-deals",
    },
  },
  {
    id: "8e5c32ce-b012-4626-aa77-fab6cefd16c1",
    slugs: {
      uz: "uklon-chegirmalar",
      ru: "uklon-skidki",
      en: "uklon-deals",
    },
  },
  {
    id: "9627a42d-e8c8-4012-81b7-672dd26d8332",
    slugs: {
      uz: "dodo-pizza-chegirmalar",
      ru: "dodo-pitstsa-skidki",
      en: "dodo-pizza-deals",
    },
  },
  {
    id: "35bfe7c4-f181-4d06-95ef-de6339ed1031",
    slugs: {
      uz: "bellissimo-pizza-chegirmalar",
      ru: "bellissimo-pizza-skidki",
      en: "bellissimo-pizza-deals",
    },
  },
  {
    id: "2ef2b1fa-5a2d-43b1-a35d-0cdf51a005fd",
    slugs: {
      uz: "cursor-chegirmalar",
      ru: "cursor-skidki",
      en: "cursor-deals",
    },
  },
  {
    id: "407f8aec-2e46-4c43-9450-ed5b5f452364",
    slugs: {
      uz: "korzinka-go-chegirmalar",
      ru: "korzinka-go-skidki",
      en: "korzinka-go-deals",
    },
  },
  {
    id: "9913684d-e528-4b1f-8004-23dd8e9c562b",
    slugs: {
      uz: "sqb-mobile-chegirmalar",
      ru: "sqb-mobile-skidki",
      en: "sqb-mobile-deals",
    },
  },
  {
    id: "85d44495-7e73-4914-8504-c6d921044b14",
    slugs: {
      uz: "payme-chegirmalar",
      ru: "payme-skidki",
      en: "payme-deals",
    },
  },
];
