import type { Language } from "../../lib/i18n";

type SlugMap = Record<Language, string>;

type MappingItem = {
  id: string;
  slugs: SlugMap;
};

/**
 * Category slug mapping with competitor differentiation
 * Auto-generated by scripts/migrations/generate-slug-mappings.ts — review before apply.
 */
export const CATEGORY_SLUG_MAPPING: MappingItem[] = [
  {
    id: "d6ab8e4d-a5ae-4f1a-9442-dc913811f33f",
    slugs: {
      uz: "elektronika",
      ru: "elektronika",
      en: "electronics-promobozor",
    },
  },
  {
    id: "495c92fa-03f4-442c-ad37-833a5b1e41d3",
    slugs: {
      uz: "kiyim-va-moda",
      ru: "odezhda-i-moda",
      en: "fashion-promobozor",
    },
  },
  {
    id: "ae02f877-0295-49ad-9b15-542834593cf1",
    slugs: {
      uz: "oziq-ovqat-va-yetkazib-berish",
      ru: "eda-i-dostavka",
      en: "food-delivery-promobozor",
    },
  },
  {
    id: "d5671b3c-6d30-4a4d-9461-02e59e536756",
    slugs: {
      uz: "gozallik-va-parvarish",
      ru: "krasota-i-uhod",
      en: "beauty-care",
    },
  },
  {
    id: "2bc180c3-81de-4b6c-a064-a2637ba505c1",
    slugs: {
      uz: "sayohat-va-turizm",
      ru: "puteshestviya-i-turizm",
      en: "travel-promobozor",
    },
  },
  {
    id: "f9789d0e-e4fb-4e84-8ff7-60c454abebc9",
    slugs: {
      uz: "moliya-va-bank-xizmatlari",
      ru: "finansy-i-bankovskie-uslugi",
      en: "finance-banking",
    },
  },
  {
    id: "5b422c21-a55d-42b7-b325-94f4dae274df",
    slugs: {
      uz: "dasturlash-va-it-xizmatlari",
      ru: "programmirovanie-i-it-uslugi",
      en: "programming-it-services",
    },
  },
  {
    id: "933a9fa4-4ed3-411a-8fb0-891ad64f3236",
    slugs: {
      uz: "kripto-va-web3",
      ru: "kripto-i-web3",
      en: "crypto-web3",
    },
  },
  {
    id: "f5de4fbb-f6f6-4a9b-8f72-87641c1260d5",
    slugs: {
      uz: "fitness-va-sport",
      ru: "fitnes-i-sport",
      en: "fitness-sport",
    },
  },
];
