import "dotenv/config";

import { and, asc, eq } from "drizzle-orm";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { db } from "../../db";
import {
  brands,
  brandTranslations,
  categories,
  categoryTranslations,
  promocodes,
  promocodeTranslations,
  stores,
  storeTranslations,
} from "../../db/schema";
import {
  differentiateFromCompetitor,
  ensureUniqueSlug,
  generateBrandSeoSlug,
  generateCategorySeoSlug,
  generatePromocodeSeoSlug,
  generateStoreSeoSlug,
  stripPromocodeCode,
} from "../../lib/slug-seo";
import { generateSlug } from "../../lib/slug";

const LOCALES = ["uz", "ru", "en"] as const;
type Locale = (typeof LOCALES)[number];

const COMPETITOR_CATEGORY_SLUGS = new Set([
  "travel",
  "fashion",
  "food-delivery",
  "electronics",
  "beauty",
  "finance",
  "crypto",
]);

type SlugMap = Record<Locale, string>;

function formatMappingFile(
  exportName: string,
  comment: string,
  items: Array<{ id: string; slugs: SlugMap }>
): string {
  const body = items
    .map((item) => {
      return `  {
    id: ${JSON.stringify(item.id)},
    slugs: {
      uz: ${JSON.stringify(item.slugs.uz)},
      ru: ${JSON.stringify(item.slugs.ru)},
      en: ${JSON.stringify(item.slugs.en)},
    },
  },`;
    })
    .join("\n");

  return `import type { Language } from "../../lib/i18n";

type SlugMap = Record<Language, string>;

type MappingItem = {
  id: string;
  slugs: SlugMap;
};

/**
 * ${comment}
 * Auto-generated by scripts/migrations/generate-slug-mappings.ts — review before apply.
 */
export const ${exportName}: MappingItem[] = [
${body}
];
`;
}

async function generateStoreMappings(): Promise<Array<{ id: string; slugs: SlugMap }>> {
  const rows = await db
    .select({
      storeId: stores.id,
      language: storeTranslations.language,
      name: storeTranslations.name,
    })
    .from(stores)
    .innerJoin(storeTranslations, eq(storeTranslations.storeId, stores.id))
    .orderBy(asc(stores.createdAt));

  const byId = new Map<string, Partial<Record<Locale, string>>>();
  const names = new Map<string, Partial<Record<Locale, string>>>();
  for (const row of rows) {
    if (!byId.has(row.storeId)) byId.set(row.storeId, {});
    if (!names.has(row.storeId)) names.set(row.storeId, {});
    names.get(row.storeId)![row.language as Locale] = row.name;
  }

  const used: Record<Locale, Map<string, string>> = {
    uz: new Map(),
    ru: new Map(),
    en: new Map(),
  };

  const items: Array<{ id: string; slugs: SlugMap }> = [];
  for (const [id, nameByLang] of names) {
    const slugs = {} as SlugMap;
    for (const locale of LOCALES) {
      const name = nameByLang[locale];
      if (!name) continue;
      slugs[locale] = ensureUniqueSlug(
        generateStoreSeoSlug({ storeName: name, language: locale }),
        used[locale],
        id
      );
    }
    if (LOCALES.every((l) => slugs[l])) {
      items.push({ id, slugs });
      void byId;
    }
  }
  return items;
}

async function generateCategoryMappings(): Promise<Array<{ id: string; slugs: SlugMap }>> {
  const rows = await db
    .select({
      categoryId: categories.id,
      language: categoryTranslations.language,
      name: categoryTranslations.name,
    })
    .from(categories)
    .innerJoin(categoryTranslations, eq(categoryTranslations.categoryId, categories.id))
    .orderBy(asc(categories.createdAt));

  const names = new Map<string, Partial<Record<Locale, string>>>();
  for (const row of rows) {
    if (!names.has(row.categoryId)) names.set(row.categoryId, {});
    names.get(row.categoryId)![row.language as Locale] = row.name;
  }

  const used: Record<Locale, Map<string, string>> = {
    uz: new Map(),
    ru: new Map(),
    en: new Map(),
  };

  const items: Array<{ id: string; slugs: SlugMap }> = [];
  for (const [id, nameByLang] of names) {
    const slugs = {} as SlugMap;
    for (const locale of LOCALES) {
      const name = nameByLang[locale];
      if (!name) continue;
      const natural = generateCategorySeoSlug({ categoryName: name, language: locale });
      const differentiated = differentiateFromCompetitor(natural, COMPETITOR_CATEGORY_SLUGS);
      slugs[locale] = ensureUniqueSlug(differentiated, used[locale], id);
    }
    if (LOCALES.every((l) => slugs[l])) {
      items.push({ id, slugs });
    }
  }
  return items;
}

async function generateBrandMappings(): Promise<Array<{ id: string; slugs: SlugMap }>> {
  const rows = await db
    .select({
      brandId: brands.id,
      language: brandTranslations.language,
      name: brandTranslations.name,
    })
    .from(brands)
    .innerJoin(brandTranslations, eq(brandTranslations.brandId, brands.id))
    .orderBy(asc(brands.createdAt));

  const names = new Map<string, Partial<Record<Locale, string>>>();
  for (const row of rows) {
    if (!names.has(row.brandId)) names.set(row.brandId, {});
    names.get(row.brandId)![row.language as Locale] = row.name;
  }

  const used: Record<Locale, Map<string, string>> = {
    uz: new Map(),
    ru: new Map(),
    en: new Map(),
  };

  const items: Array<{ id: string; slugs: SlugMap }> = [];
  for (const [id, nameByLang] of names) {
    const slugs = {} as SlugMap;
    for (const locale of LOCALES) {
      const name = nameByLang[locale];
      if (!name) continue;
      slugs[locale] = ensureUniqueSlug(
        generateBrandSeoSlug({ brandName: name, language: locale }),
        used[locale],
        id
      );
    }
    if (LOCALES.every((l) => slugs[l])) {
      items.push({ id, slugs });
    }
  }
  return items;
}

async function generatePromocodeMappings(): Promise<Array<{ id: string; slugs: SlugMap }>> {
  const rows = await db
    .select({
      promocodeId: promocodes.id,
      code: promocodes.code,
      discountPercent: promocodes.discountValue,
      language: promocodeTranslations.language,
      title: promocodeTranslations.title,
      storeName: storeTranslations.name,
      brandName: brandTranslations.name,
    })
    .from(promocodes)
    .innerJoin(promocodeTranslations, eq(promocodeTranslations.promocodeId, promocodes.id))
    .leftJoin(stores, eq(stores.id, promocodes.storeId))
    .leftJoin(
      storeTranslations,
      and(
        eq(storeTranslations.storeId, stores.id),
        eq(storeTranslations.language, promocodeTranslations.language)
      )
    )
    .leftJoin(brands, eq(brands.id, promocodes.brandId))
    .leftJoin(
      brandTranslations,
      and(
        eq(brandTranslations.brandId, brands.id),
        eq(brandTranslations.language, promocodeTranslations.language)
      )
    )
    .orderBy(asc(promocodes.createdAt));

  type Meta = {
    code: string | null;
    discountPercent: number | null;
    titles: Partial<Record<Locale, string>>;
    hubNames: Partial<Record<Locale, string>>;
  };

  const byId = new Map<string, Meta>();
  for (const row of rows) {
    if (!byId.has(row.promocodeId)) {
      byId.set(row.promocodeId, {
        code: row.code,
        discountPercent: row.discountPercent,
        titles: {},
        hubNames: {},
      });
    }
    const meta = byId.get(row.promocodeId)!;
    meta.titles[row.language as Locale] = row.title;
    const hub = row.storeName || row.brandName;
    if (hub) {
      meta.hubNames[row.language as Locale] = hub;
    }
  }

  const used: Record<Locale, Map<string, string>> = {
    uz: new Map(),
    ru: new Map(),
    en: new Map(),
  };

  const items: Array<{ id: string; slugs: SlugMap }> = [];
  for (const [id, meta] of byId) {
    const slugs = {} as SlugMap;
    for (const locale of LOCALES) {
      const title = meta.titles[locale];
      if (!title) continue;
      const hubName = meta.hubNames[locale];
      const natural = hubName
        ? generatePromocodeSeoSlug({
            storeName: hubName,
            title,
            code: meta.code,
            discountPercent: meta.discountPercent,
            language: locale,
          })
        : generateSlug(stripPromocodeCode(title, meta.code));
      slugs[locale] = ensureUniqueSlug(natural || "chegirma", used[locale], id);
    }
    if (LOCALES.every((l) => slugs[l])) {
      items.push({ id, slugs });
    }
  }
  return items;
}

async function main() {
  const dir = path.dirname(new URL(import.meta.url).pathname);

  const [storeItems, categoryItems, brandItems, promocodeItems] = await Promise.all([
    generateStoreMappings(),
    generateCategoryMappings(),
    generateBrandMappings(),
    generatePromocodeMappings(),
  ]);

  writeFileSync(
    path.join(dir, "store-slug-mapping.ts"),
    formatMappingFile(
      "STORE_SLUG_MAPPING",
      "Store slug mapping: {name}-chegirmalar/skidki/deals",
      storeItems
    )
  );
  writeFileSync(
    path.join(dir, "category-slug-mapping.ts"),
    formatMappingFile(
      "CATEGORY_SLUG_MAPPING",
      "Category slug mapping with competitor differentiation",
      categoryItems
    )
  );
  writeFileSync(
    path.join(dir, "brand-slug-mapping.ts"),
    formatMappingFile(
      "BRAND_SLUG_MAPPING",
      "Brand slug mapping: {name}-chegirmalar/skidki/deals",
      brandItems
    )
  );
  writeFileSync(
    path.join(dir, "promocode-slug-mapping.ts"),
    formatMappingFile(
      "PROMOCODE_SLUG_MAPPING",
      "Promocode slug mapping: store + benefit, code-stripped",
      promocodeItems
    )
  );

  console.log("✅ Generated mapping files:");
  console.log(`  stores: ${storeItems.length}`);
  console.log(`  categories: ${categoryItems.length}`);
  console.log(`  brands: ${brandItems.length}`);
  console.log(`  promocodes: ${promocodeItems.length}`);
}

main().catch((error) => {
  console.error("❌ Failed to generate mappings:", error);
  process.exit(1);
});
