import type { Language } from "../../lib/i18n";

type SlugMap = Record<Language, string>;

type MappingItem = {
  id: string;
  slugs: SlugMap;
};

/**
 * Promocode slug mapping: store + benefit, code-stripped
 * Auto-generated by scripts/migrations/generate-slug-mappings.ts — review before apply.
 */
export const PROMOCODE_SLUG_MAPPING: MappingItem[] = [
  {
    id: "1cd8cdf9-b216-403d-8882-35c190cd4240",
    slugs: {
      uz: "glm-ai-coding-plan-20-chegirma",
      ru: "glm-ai-coding-plan-skidka-20",
      en: "glm-ai-coding-plan-20-off",
    },
  },
  {
    id: "a91e6349-47ac-47a3-89e3-d618fde3d7e8",
    slugs: {
      uz: "yandex-market-30-000-som-chegirma",
      ru: "yandeks-market-skidka-30-000-sum-v",
      en: "yandex-market-30000-uzs-discount-at",
    },
  },
  {
    id: "dbc05965-2923-4d36-bd32-ce586bd7a1ef",
    slugs: {
      uz: "yandex-eats-40-000-som-chegirma-birinchi-buyurtma-uchun",
      ru: "yandeks-eda-skidka-40-000-sum-na-pervyy-zakaz",
      en: "yandex-eats-40000-uzs-discount-on-first-order",
    },
  },
  {
    id: "e29071f6-8c0d-4d87-8e86-f0cd89794eaa",
    slugs: {
      uz: "iherb-rasmiy-dokoni-birinchi-buyurtmada-20-gacha-chegirma",
      ru: "ofitsialnyy-magazin-iherb-skidka-do-20-na-pervyy-zakaz",
      en: "official-iherb-store-up-to-20-off-first-order",
    },
  },
  {
    id: "ec820779-6c34-4efc-8a42-ddbec9746b65",
    slugs: {
      uz: "uzum-bank-bepul-visa-va-30-chegirmalar",
      ru: "uzum-bank-besplatnaya-karta-skidki-do-30",
      en: "uzum-bank-free-card-up-to-30-discounts",
    },
  },
  {
    id: "64464d50-f8be-4cfe-9990-c962732b32a7",
    slugs: {
      uz: "mutolaa-premium-uchun-10-chegirma",
      ru: "mutolaa-skidka-10-na-premium",
      en: "mutolaa-10-discount-on-premium",
    },
  },
  {
    id: "c1bf64c1-55dc-40b6-9538-2f62f4a6e559",
    slugs: {
      uz: "tbc-bank-salom-card-oching-va-30-000-som-bonus-oling",
      ru: "tbc-bank-otkroyte-salom-card-i-poluchite-30-000-sumov-30000-skidka",
      en: "tbc-bank-get-30000-uzs-bonus-with-salom-card",
    },
  },
  {
    id: "8f4e736b-5ec2-4676-a94a-01225c080208",
    slugs: {
      uz: "tbc-bank-omonati-400-000-somgacha-bonus",
      ru: "tbc-bank-bonus-do-400-000-sumov-na-vklady",
      en: "tbc-bank-up-to-400000-uzs-bonus-for-deposits",
    },
  },
  {
    id: "3a8ebb7a-9f02-4261-90c4-816febfae29f",
    slugs: {
      uz: "tbc-bank-osmon-card-oching-va-50-000-som-bonus-oling",
      ru: "tbc-bank-otkroyte-osmon-card-i-poluchite-50-000-sumov-50000-skidka",
      en: "tbc-bank-get-50000-uzs-bonus-with-osmon-card",
    },
  },
  {
    id: "f6d67a89-8142-4b3e-99e2-16d55831fd4a",
    slugs: {
      uz: "hostinger-20-chegirma-va-bepul-domen",
      ru: "hostinger-skidka-20-i-besplatnyy-domen",
      en: "hostinger-20-off-free-domain",
    },
  },
  {
    id: "4f63850e-4497-4165-ae3e-d7caafa57516",
    slugs: {
      uz: "digitalocean-200-bepul-kredit-bonus",
      ru: "digitalocean-200-kredit-besplatno-bonus",
      en: "digitalocean-200-free-credit-bonus",
    },
  },
  {
    id: "eb22a347-079a-487c-a8a6-d9888fbf980d",
    slugs: {
      uz: "railway-boshlangich-kredit-va-oson-deployed-20-chegirma",
      ru: "railway-startovyy-kredit-i-legkiy-deploy-20-skidka",
      en: "railway-starting-credit-easy-deployment-20-discount",
    },
  },
  {
    id: "9e317922-1dd3-4b30-9e0b-778435e5a948",
    slugs: {
      uz: "v0-oyiga-200-gacha-bepul-kredit-oling",
      ru: "v0-poluchite-kredity-do-20-skidka",
      en: "v0-get-up-to-in-credits-20-discount",
    },
  },
  {
    id: "3b95dbec-f001-4575-a02d-ede7cf1a7067",
    slugs: {
      uz: "jet-2-ta-skuter-safari-uchun-50-chegirma",
      ru: "jet-50-na-2-poezdki-samokate",
      en: "jet-50-off-2-scooter-rides",
    },
  },
  {
    id: "a88a13e5-20bc-4fe8-9d84-2f469a035c3d",
    slugs: {
      uz: "domo-kommunal-tolovlar-ilovasi",
      ru: "domo-oplata-kommunalnyh-uslug",
      en: "domo-utility-payments-app",
    },
  },
  {
    id: "e9ce0912-ddfc-4303-b83e-d9038724c7d0",
    slugs: {
      uz: "jett",
      ru: "jett",
      en: "jett",
    },
  },
  {
    id: "76321585-ff4f-48a1-bc7e-9d8500274b1a",
    slugs: {
      uz: "ibrat-akademy",
      ru: "ibrat-akademy",
      en: "ibrat-akademy",
    },
  },
  {
    id: "a7ccc8e7-e5ef-42ee-929c-5e725b65e754",
    slugs: {
      uz: "opal-30-kun-pro",
      ru: "opal-30-dney-pro",
      en: "opal-30-day-pro-pass",
    },
  },
  {
    id: "a60f7cf2-d3ac-4385-b75f-1d12a21a72c4",
    slugs: {
      uz: "uzum-bank-tavsiya-45000-chegirma",
      ru: "uzum-bank-45000-skidka",
      en: "uzum-bank-45000-discount",
    },
  },
  {
    id: "40e2b266-5363-4270-aec5-0898c9d143ab",
    slugs: {
      uz: "don-donga-azo-boling-bonus",
      ru: "don-prisoedinyaytes-k-referalnyy-bonus",
      en: "don-join-bonus",
    },
  },
  {
    id: "660a7304-e89f-4345-bbc7-e889eb27bf55",
    slugs: {
      uz: "hevy-mashgulot-tracking-ilovasi",
      ru: "hevy-prilozhenie-dlya-otslezhivaniya-trenirovok",
      en: "hevy-workout-tracker-app",
    },
  },
  {
    id: "24e86629-6345-4683-964e-28d7b4e6563f",
    slugs: {
      uz: "korzinka-40-000-som-chegirma",
      ru: "korzinka-skidka-40-000-sum",
      en: "korzinka-40000-uzs-discount",
    },
  },
  {
    id: "96f78db2-0a13-4e2f-90cf-76a3bc184239",
    slugs: {
      uz: "1fit-7-kun-bepul-trial",
      ru: "1fit-7-dney-besplatnyy-trial",
      en: "1fit-7-days-free-trial",
    },
  },
  {
    id: "2a3ea563-153e-48fa-83cc-05ea826928a2",
    slugs: {
      uz: "uklon-70-gacha-chegirma-birinchi-safar-uchun",
      ru: "uklon-skidka-do-70-na-pervuyu-poezdku",
      en: "uklon-up-to-70-off-first-ride",
    },
  },
  {
    id: "6f0d516e-6a51-4e77-b29f-cf9b8ad61159",
    slugs: {
      uz: "dodo-pizza-30-chegirma-birinchi-buyurtma",
      ru: "dodo-pitstsa-30-skidka-na-pervyy-zakaz",
      en: "dodo-pizza-30-discount-on-first-order",
    },
  },
  {
    id: "819a7ac4-9f91-4eb5-8d06-052eab1564dd",
    slugs: {
      uz: "bellissimo-pizza-30-000-som-chegirma-birinchi-buyurtma-uchun",
      ru: "bellissimo-pizza-skidka-30-000-sum-na-pervyy-zakaz",
      en: "bellissimo-pizza-30000-uzs-discount-on-first-order",
    },
  },
  {
    id: "083ea5f3-d02e-4c4f-a361-fa0ff311493f",
    slugs: {
      uz: "cursor-pro-birinchi-oyda-50-chegirma",
      ru: "cursor-pro-50-skidka-na-pervyy-mesyats",
      en: "cursor-pro-50-off-your-first-month",
    },
  },
  {
    id: "6fd36110-3ae5-4cfc-9cfe-edc51ed62c8d",
    slugs: {
      uz: "jet-ilovasida-royxatdan-oting-va-50-chegirma-bilan-sayohatlar",
      ru: "jet-registriruytes-v-prilozhenii-i-poluchayte-50-skidku-na-poezdki",
      en: "jet-sign-up-for-app-and-get-50-discount-on-rides",
    },
  },
  {
    id: "6fd683c9-7505-4621-b22a-faf2bb986406",
    slugs: {
      uz: "korzinka-go-ilk-buyurtmaga-30-000-som-chegirma",
      ru: "korzinka-go-skidka-30-000-sum-na-pervyy-zakaz",
      en: "korzinka-go-30000-uzs-off-your-first-order",
    },
  },
  {
    id: "2659abaf-37f6-49b9-b73d-5cf602df4220",
    slugs: {
      uz: "sqb-mobile-dostni-taklif-qilib-5-000-som-bonus",
      ru: "sqb-mobile-bonus-5-000-sum-za-priglashenie-druzey",
      en: "sqb-mobile-5000-uzs-bonus-for-inviting-friends",
    },
  },
  {
    id: "9ed64d0a-ab31-4330-88b5-f5f1a3f2eec1",
    slugs: {
      uz: "hostinger-premium-20-chegirma-12-oy",
      ru: "hostinger-premium-skidka-20-12-mesyatsev",
      en: "hostinger-premium-20-off-12-months",
    },
  },
  {
    id: "ed4bd78c-3768-428c-9fdb-ff75ae13f99a",
    slugs: {
      uz: "hostinger-business-20-chegirma-eng-mashhur",
      ru: "hostinger-business-skidka-20-samyy-populyarnyy",
      en: "hostinger-business-20-off-most-popular",
    },
  },
  {
    id: "ae7906d2-4e7f-4b3c-9bc5-e07ed1246d66",
    slugs: {
      uz: "hostinger-cloud-startup-20-chegirma",
      ru: "hostinger-cloud-startup-skidka-20",
      en: "hostinger-cloud-startup-20-off",
    },
  },
  {
    id: "af7e79b4-9c2e-40ed-81ca-31765c9a6b4c",
    slugs: {
      uz: "payme-plus-30-kun-bepul-hammasi-ichida-100-chegirma",
      ru: "payme-plus-30-dney-besplatno-vse-vklyucheno-100-skidka",
      en: "payme-plus-30-days-free-all-inclusive-100-discount",
    },
  },
];
