import type { Language } from "../../lib/i18n";

type SlugMap = Record<Language, string>;

type MappingItem = {
  id: string;
  slugs: SlugMap;
};

/**
 * Store slug mapping: {name}-chegirmalar/skidki/deals
 * Auto-generated by scripts/migrations/generate-slug-mappings.ts — review before apply.
 */
export const STORE_SLUG_MAPPING: MappingItem[] = [
  {
    id: "29ee7919-8fd4-4c85-b889-a50b08f8924a",
    slugs: {
      uz: "yandex-market-chegirmalar",
      ru: "yandeks-market-skidki",
      en: "yandex-market-deals",
    },
  },
  {
    id: "9c5a8757-fc4f-4a00-b9d6-b87ab6959de6",
    slugs: {
      uz: "uzum-market-chegirmalar",
      ru: "uzum-market-skidki",
      en: "uzum-market-deals",
    },
  },
  {
    id: "6871cfa3-1445-4a1d-8580-731ea6214b23",
    slugs: {
      uz: "iherb-rasmiy-dokoni-chegirmalar",
      ru: "ofitsialnyy-magazin-iherb-skidki",
      en: "official-iherb-store-deals",
    },
  },
  {
    id: "f0091021-9ce7-4259-bd46-a07ae77620a2",
    slugs: {
      uz: "don-chegirmalar",
      ru: "don-skidki",
      en: "don-deals",
    },
  },
  {
    id: "2150f4be-b702-4083-bcf6-76a650fb6bef",
    slugs: {
      uz: "korzinka-chegirmalar",
      ru: "korzinka-skidki",
      en: "korzinka-deals",
    },
  },
];
